### ISSUE TITLE
macos failed to start recording

### ISSUE THREAD

**Issue by flutter-painter** [MarekRudzki/TalkBridge#6]
flutter: Start recording
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-3, Failed to start recording, Input device not found from available list., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      VoiceRecorder.build.startRecording (package:talkbridge/features/voice_record/presentation/widgets/voice_recorder.dart:40:9)
<asynchronous suspension>
#3      VoiceRecorder.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:talkbridge/features/voice_record/presentation/widgets/voice_recorder.dart:162:29)
<asynchronous suspension>

**Comment by MarekRudzki** [comment]
Hi.
The described issue is probably caused by missing permissions. I have updated the code. Unfortunately, currently I do not have access to macOS device, so if you could check if the issue still occurs I would be really grateful. Thanks in advance

**Comment by flutter-painter** [comment]
Hi @MarekRudzki,

Indeed it comes from the entitlements,
example/macos/Runner/DebugProfile.entitlements
macos/Runner/DebugProfile.entitlements
macos/Runner/Release.entitlements
We need to add :

<key>com.apple.security.device.audio-input</key>
<true/>

Also since the app uses internet, also need to add : 

<key>com.apple.security.network.client</key>
<true/>

**Comment by MarekRudzki** [comment]
HI @flutter-painter,
thanks for suggestions, I have added required entitlements.
